# version: "3.9"
# services:
#   backend:
#     build: ./backend
#     container_name: backend
#     env_file:
#       - ./backend/.env
#     ports:
#       - "8000:8000"
#     depends_on:
#       - db
#       - redis

#   db:
#     image: postgres:15
#     container_name: postgres
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: postgres
#       POSTGRES_DB: fraud_db
#     ports:
#       - "5432:5432"

#   redis:
#     image: redis:7
#     container_name: redis
#     ports:
#       - "6379:6379"





# version: "3.9"
# services:
#   backend:
#     build: ./backend
#     container_name: backend
#     env_file:
#       - ./backend/.env
#     ports:
#       - "8080:8000" 
#     depends_on:
#       - db
#       - redis

#   frontend:
#     build: ./frontend
#     container_name: frontend
#     ports:
#       - "3000:80"           # maps container port 80 (nginx) to host 3000
#     depends_on:
#       - backend

#   db:
#     image: postgres:15
#     container_name: postgres
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: postgres
#       POSTGRES_DB: fraud_db
#     ports:
#       - "5432:5432"

#   redis:
#     image: redis:7
#     container_name: redis
#     ports:
#       - "6379:6379"



version: "3.9"

services:
  backend:
    build: ./backend
    container_name: backend
    env_file:
      - ./backend/.env
    ports:
      - "8080:8000"
    depends_on:
      - db
      - redis
    environment:
      # Use Docker service names for internal networking
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@db:5432/fraud_db
      REDIS_URL: redis://redis:6379/0

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  db:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fraud_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:
